main:
  push:
    - runner:
        cpus: 2
      docker:
        image: python:3.12
      imports: 
        - https://cnb.cool/xzzlwl/pypi-api-token/-/blob/main/env.yaml
        - https://cnb.cool/xzzlwl/wxwork-push-url/-/blob/main/env.yml
      stages:
        - name: Dry-run Tests
          jobs:
          - name: Run Tests
            script:
              - python -m pip install -U pip
              - python -m pip install -e .[dev]
              - export QWSEND_WEBHOOK_KEY=$WXWORK_MYSELF_WEBHOOK_KEY
              - qwsend text "hello from TestPyPI build at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
              - pytest -v
        - name: Build and Upload to TestPyPI
          jobs:
          - name: Build Package
            script:
              - python -m pip install -U build twine
              - python -m build
              - python -m twine check dist/*
          - name: Upload to TestPyPI
            script:
              - python -m twine upload --verbose dist/* -u __token__ -p $TESTPYPI_TOKEN --repository testpypi --skip-existing
CNB:
  push:
    - runner:
        cpus: 2
      services:
        - docker
      stages:
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest