main:
  push:
    - runner:
        cpus: 2
      docker:
        image: python:3.12
      imports: 
        - https://cnb.cool/xzzlwl/pypi-api-token/-/blob/main/env.yaml
        - https://cnb.cool/xzzlwl/wxwork-push-url/-/blob/main/env.yml
      stages:
        - name: Dry-run Tests
          jobs:
          - name: Run Tests Excluding Wet Tests
            script:
              - python -m pip install -U pip
              - python -m pip install -e .[dev]
              - pytest -v
        - name: Build and Upload to TestPyPI
          jobs:
          - name: Build Package
            script:
              - python -m pip install -U build twine
              - python -m build
              - python -m twine check dist/*
          - name: Upload to TestPyPI
            script:
              - python -m twine --verbose upload dist/* -u __token__ -p $TESTPYPI_TOKEN --repository testpypi 
          - name: Install from TestPyPI
            script:
              - python -m pip install --index-url https://test.pypi.org/simple/ qwsend
              - export QWSEND_WEBHOOK_KEY=$WXWORK_MYSELF_WEBHOOK_KEY
              - qwsend "hello from TestPyPI build"